theme: cube

# background display for mobile, not for pc
#
header:
  background: http://raw.githubusercontent.com/sumnear/blog/master/httpFiles/hzw1.jpg
  #background: http://cube-1252774894.cosgz.myqcloud.com/background.png
  # both pc and mobile required title(make it the same as your hexo site _config.yml's title)
  title: Sumnear's coding life
  subtitle: SEARCH FOR MY ONE PIECE


# background display for pc
# you can use url or path relative
# `background: background.png` refers to the path "source/images/background.png"
background: http://raw.githubusercontent.com/sumnear/blog/master/httpFiles/hzw1.jpg


# the background image width and height (you can see your image file to get them)
width: 2000
height: 1414


# this variable is used to locate your background
# for example, if you want to locate display your background from top
# you just need to type it: position: 0
#position: 400
position: 200

# this variable is used to make the background header being fuzzy
# if your do not need the filter blur on the top, make it empty, it means that: `blur: `
blur: 5


# yeah, it is just to make your avatar rounded(true) or not(false)
avatar: true

menu:
  # index
  - title: 首页
    icon: home
    url: /
  # archives
  - title: 归档
    icon: archive
    url: archives
  # categories
  - title: 分类
    icon: categories
    url: categories
  # tags
  - title: 标签
    icon: tags
    url: tags
  # about-me
  - title: 关于我
    icon: about
    url: about-me

sidebar:
  links:
    - title: GitHub
      url: https://github.com/sumnear
      # icon can be url or path
      icon: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/GitHub.png
    - title: gitee
      url: https://gitee.com/SumTeam
      icon: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/mayun.jpg
    - title: 网易云
      url: https://music.163.com/#/user/home?id=109182388
      icon: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/wangyiyun.jpg
   # - title: SF社区
  #    url: https://segmentfault.com/u/aonosora
   #   icon: http://cube-1252774894.cosgz.myqcloud.com/links/SF.png
  #  - title: 开发者头条
  #    url: https://toutiao.io/u/148070
  #    icon: http://cube-1252774894.cosgz.myqcloud.com/links/开发者头条.png
  friend_links:
    - title: 主题作者
      url: http://ZEROKISEKI.github.io
      # icon only url
    - title: 推荐人糜
      url: https://mrkaorou.github.io
      icon: https://mrkaorou.github.io/images/avatar.jpeg


# only path, refer to source/images
#themes/hexo-theme-cube/source/images/friend_links.jpg
friend_links: friend_links.jpg

widgets:
- search
- author
- music
- recent_posts
- categories
- tagcloud
- links
- friend_links

# when you want to use the search, firstly make the `search: true`,
# then you should install hexo-generator-json-content
# run `npm install hexo-generator-json-content -save` (in your hexo directory)
search: true

# supported by DIYgod awesome project APlayer, you can find more on https://github.com/MoePlayer/APlayer
# and you can see the doc on https://aplayer.js.org/docs/#/

# mode can be `random`, `single`, `circulation`(loop), `order`(no loop)
# if you have the lrc file, make the `showlrc` true, else make it false
music_setting:
  auto: false
  mode: circulation
  narrow: false
  mutex: true
  showlrc: false
  theme:
  preload: auto
  maxHeight: 513px

# if you use path, make sure your hexo _config.yml has set the correcting url
# url: http://www.yoururl.com/path/to/.mp3 or .lrc or ...
# you'd better place your music and image, lrc to another site, and use url instead of path
# if you don't want to use this widget, just make that `music: `
music:
  - title: PerfectTime
    author: 泽野弘之
    source: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/PerfectTime.mp3
    #lrc: http://cube-1252774894.cosgz.myqcloud.com/music/lrc/Dear friends - TRIPLANE.lrc
    image: http://raw.githubusercontent.com/sumnear/blog/master/httpFiles/PerfectTime.png

  - title: はるかな旅
    author: 吉田洁
    source: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/はるかな旅.mp3
    #lrc: http://cube-1252774894.cosgz.myqcloud.com/music/lrc/Dear friends - TRIPLANE.lrc
    image: http://raw.githubusercontent.com/sumnear/blog/master/httpFiles/PerfectTime.png

  - title: 春风再美也比不上你的笑，没见过你的人自然不会明了
    author: 十指流玉
    source: https://raw.githubusercontent.com/sumnear/blog/master/httpFiles/春风再美也比不上你的笑，没见过你的人自然不会明了.mp3
    #lrc: http://cube-1252774894.cosgz.myqcloud.com/music/lrc/Dear friends - TRIPLANE.lrc
    image: http://raw.githubusercontent.com/sumnear/blog/master/httpFiles/PerfectTime.png
# before using the comment
# make use you know how to set the params

#评论功能
comment:
  # your disqus_shortname
  disqus:
  changyan:
    appid: cytVJyyCD
    conf: prod_f0e5e9a4bba3527f30be0c5785b04553
  youyan:
  # gitment: https://github.com/imsun/gitment
  # make sure you know how to set it
  gitment:
    owner:
    repo:
    oauth:
      client_id:
      client_secret:

  #如果您使用了畅言, 要把畅言的浮动框 or 弹出框去掉, 可以进行下面的配置:
# some setting about comment module
comment_setting:
  changyan:
    hide_notice: true

analytics:
  baidu: b16dbde837be836c56dfa2bd15c1bb4c
  google:
  